### ISSUE TITLE
Does not compile with the GIL-free version of Python 3.13

### ISSUE THREAD

**Issue by cphyc** [yt-project/ewah_bool_utils#112]
When trying to compile on Python 3.13.0rc1 with the `gil` disabled, I get an error at compilation time:

```bash
$ python --version                                                                                  
Python 3.13.0rc1
$ python -c "import sys; print(sys._is_gil_enabled())"
False
$ python -m pip install -v .   # from the folder containing the source
[...]
__Pyx_CyFunction_CallAsMethod(PyObject*, PyObject*, PyObject*)’:
  ewah_bool_utils/ewah_bool_wrap.cpp:58695:6: error: ‘__pyx_vectorcallfunc’ was not declared in this scope; did you mean ‘vectorcallfunc’?
  58695 |      __pyx_vectorcallfunc vc = __Pyx_CyFunction_func_vectorcall(cyfunc);
        |      ^~~~~~~~~~~~~~~~~~~~
        |      vectorcallfunc
  ewah_bool_utils/ewah_bool_wrap.cpp:58696:9: error: ‘vc’ was not declared in this scope
  58696 |     if (vc) {
        |         ^~
  error: command '/usr/bin/g++' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for ewah_bool_utils (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/cphyc/tmp/py313t/bin/python /home/cphyc/tmp/py313t/lib/python3.13t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmp7atobsfo
  cwd: /home/cphyc/Documents/prog/ewah_bool_utils
  Building wheel for ewah_bool_utils (pyproject.toml) ... error
  ERROR: Failed building wheel for ewah_bool_utils
Failed to build ewah_bool_utils
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (ewah_bool_utils)
```

This is likely related to the C-API changing with the `gil`-free version of Python, see https://github.com/cython/cython/issues/6162.

Note that the compilation works on Python 3.13, with the GIL enabled.

**Comment by neutrinoceros** [comment]
> Note that the compilation works on Python 3.13, with the GIL enabled.

I should hope so, we already have cp313 wheels up on PyPI :)

What version of Cython are you using ? The dev branch is supposed to fix a lot of issues with free-threaded builds, but the latest stable version (3.0.11) is known broken.

**Comment by cphyc** [comment]
Indeed, I tried with `Cython version 3.1.0a0` and it compiles and passes all tests just fine.

**Comment by neutrinoceros** [comment]
FYI, Cython 3.1 is finally here https://github.com/cython/cython/releases/tag/3.1.0
let me know if you find anything's missing in ewah.
